package controllers

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	MCADImage       = "quay.io/ksuta/mcad-controller:dev"
	InstaScaleImage = "quay.io/ksuta/instascale-controller:v0.0.4"
)
