package controllers

// ***********************
//  DO NOT EDIT THIS FILE
// ***********************

const (
	MCADImage       = "quay.io/ksuta/mcad-controller:release-v1.32.0"
	InstaScaleImage = "quay.io/ksuta/instascale-controller:v0.0.6"
)
