apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: codeflare-stack-config
  envs:
    - bases/params.env
configurations:
  - bases/params.yaml

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: codeflare-stack-config
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
- name: odh-codeflare-operator-controller-image
  objref:
    kind: ConfigMap
    name: codeflare-stack-config
    apiVersion: v1
  fieldref:
    fieldpath: data.odh-codeflare-operator-controller-image
resources:
- ../default
