# This workflow will build the CodeFlare Operator dev image and push it to the project-codeflare image registry

name: Operator Dev Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'test/**'
      - '**.adoc'
      - '**.md'
      - 'LICENSE'

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Login to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.QUAY_ID }}
        password: ${{ secrets.QUAY_TOKEN }}
        registry: quay.io

    - name: Image Build
      run: |
        make build
        make image-build -e IMG=quay.io/ksuta/codeflare-operator:dev
        make image-push -e IMG=quay.io/ksuta/codeflare-operator:dev
